### ISSUE TITLE
The Disconnect category contains a Google domain that is not remapped

### ISSUE THREAD

**Issue by englehardt** [mozilla-services/shavar-prod-lists#37]
The Disconnect category of the main blocklist file contains `googletagmanager.com` [here](https://github.com/mozilla-services/shavar-prod-lists/blob/master/disconnect-blacklist.json#L8954), however this is not included in the Google remapping file [here](https://github.com/mozilla-services/shavar-prod-lists/blob/master/google_mapping.json). Does that mean we drop `googletagmanager.com`?

**Comment by fmarier** [comment]
That's because you're looking at the wrong mapping file. That's an old one that was used (maybe still is, I'm not sure) for iOS only.

The one we use everywhere on the shavar server is https://github.com/mozilla-services/shavar-list-creation/blob/master/disconnect_mapping.py.

We should probably update the README in this repo.

**Comment by englehardt** [comment]
This was fixed in #40
